# Nav2 configuration for autonomous mower
amcl:
  ros__parameters:
    use_map_topic: false
    scan_topic: scan

map_server:
  ros__parameters:
    yaml_filename: /home/tyler/mower_ws/maps/map.yaml

planner_server:
  ros__parameters:
    planner_plugins: [GridBased]
    use_sim_time: true
    GridBased:
      plugin: nav2_smac_planner/SmacPlannerHybrid
      allow_unknown: true
      tolerance: 0.25

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: [FollowPath]
    FollowPath:
      plugin: dwb_core::DWBLocalPlanner
      debug_trajectory_details: false
      min_vel_x: 0.0
      max_vel_x: 0.8
      min_vel_theta: -1.0
      max_vel_theta: 1.0

bt_navigator:
  ros__parameters:
    use_sim_time: true

behavior_server:
  ros__parameters:
    use_sim_time: true

global_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 1.0
    publish_frequency: 1.0
    footprint: "[[0.3, 0.2], [0.3, -0.2], [-0.3, -0.2], [-0.3, 0.2]]"
    plugins: [static_layer, inflation_layer]
    static_layer:
      plugin: nav2_costmap_2d::StaticLayer
      map_subscribe_transient_local: true
    inflation_layer:
      plugin: nav2_costmap_2d::InflationLayer
      cost_scaling_factor: 2.5
      inflation_radius: 0.6

local_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    rolling_window: true
    width: 10
    height: 10
    resolution: 0.05
    footprint: "[[0.3, 0.2], [0.3, -0.2], [-0.3, -0.2], [-0.3, 0.2]]"
    plugins: [inflation_layer]
    inflation_layer:
      plugin: nav2_costmap_2d::InflationLayer
      cost_scaling_factor: 2.5
      inflation_radius: 0.6

lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names: ["map_server", "amcl", "planner_server", "controller_server", "bt_navigator", "behavior_server"]
