controller_manager:
  ros__parameters:
    update_rate: 200  # Hz - Reasonable control rate (5ms period)
    use_sim_time: true  # Ensure proper clock synchronization
    
    # Clock source configuration
    clock_interface_timeout: 3  # seconds to wait for clock source

    # List of controllers to load and start
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    reel_controller:
      type: velocity_controllers/JointGroupVelocityController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
      - reel_joint
      - front_roller_joint

    # Publishing frequency
    publish_rate: 200.0  # Hz

diff_drive_controller:
  ros__parameters:
    # Physical robot parameters from PRD
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    
    wheel_separation: 0.46  # meters (distance between wheel centers)
    wheel_radius: 0.0975    # meters (wheel radius)
    
    # Velocity and acceleration limits
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    
    # Command and odometry settings
    publish_rate: 70.0  # Hz
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    twist_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    
    # Open loop odometry (no feedback from wheels)
    open_loop: false
    
    # Publish odom->base_link transform
    enable_odom_tf: false
    
    # Command timeout
    cmd_vel_timeout: 0.5  # seconds
    
    # Topic remapping
    use_stamped_vel: false

reel_controller:
  ros__parameters:
    joints: [reel_joint]
    command_interfaces: [velocity]
    state_interfaces: [position, velocity]
