controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # List of controllers to load and start
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    reel_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
      - reel_joint
      - front_roller_joint

diff_drive_controller:
  ros__parameters:
    # Physical robot parameters from PRD
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    
    wheel_separation: 0.46  # meters (distance between wheel centers)
    wheel_radius: 0.0975    # meters (wheel radius)
    
    # Velocity and acceleration limits
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    
    # Command and odometry settings
    publish_rate: 50.0  # Hz
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    # Open loop odometry (no feedback from wheels)
    open_loop: false
    
    # Publish odom->base_link transform
    enable_odom_tf: true
    
    # Command timeout
    cmd_vel_timeout: 0.5  # seconds
    
    # Topic remapping
    use_stamped_vel: false

reel_controller:
  ros__parameters:
    joints:
      - reel_joint
    
    # Interface type
    interface_name: velocity
    
    # Command interface configuration
    command_interfaces:
      - velocity
    
    # State interface configuration  
    state_interfaces:
      - position
      - velocity
    
    # PID gains (conservative values for initial testing)
    gains:
      reel_joint:
        p: 100.0
        i: 0.0
        d: 10.0
        i_clamp_max: 1.0
        i_clamp_min: -1.0
        antiwindup: true
    
    # Physical constraints
    constraints:
      stopped_velocity_tolerance: 0.01  # rad/s
      goal_time: 2.0  # seconds
      reel_joint:
        trajectory: 0.05  # rad
        goal: 0.05        # rad
    
    # Belt reduction ratio from motor to reel (20:76 = 0.263)
    # This accounts for the belt reduction mentioned in PRD
    # Motor commands will be scaled by this factor
    gear_ratio: 0.263
