# NavSat Transform Configuration
#
# This node converts GPS lat/lon coordinates to Cartesian coordinates in the map frame.
# It subscribes to GPS data and publishes odometry messages for the global EKF.
#
# Inputs: GPS fix data, IMU orientation, local EKF odometry
# Output: /odometry/gps in 'map' frame

navsat_transform:
  ros__parameters:
    frequency: 20.0
    delay: 0.0
    magnetic_declination_radians: 0.0
    yaw_offset: 1.5707963  # 90 degrees
    zero_altitude: true
    publish_filtered_gps: false
    use_odometry_yaw: false
    wait_for_datum: false

    # Frames
    base_link_frame: base_link
    odom_frame: odom
    world_frame: map
