# NavSat Transform Configuration
#
# This node converts GPS lat/lon coordinates to Cartesian coordinates in the UTM frame.
# It publishes /odometry/gps in the UTM frame for the single EKF fusion.
#
# Inputs: GPS fix data, IMU orientation, local EKF odometry
# Output: /odometry/gps in 'utm' frame

navsat_transform:
  ros__parameters:
    frequency: 20.0
    delay: 5.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    publish_filtered_gps: false
    use_odometry_yaw: false
    #wait_for_datum: true  # Use hardcoded datum for simulation
    
    # Hardcoded datum for simulation (Alabama coordinates)
    #datum: [34.6031, -86.7496, 0.0]
    
    # Frame configuration - ignore GPS sensor frame and assume at robot origin
    # broadcast_cartesian_transform: true
    # broadcast_cartesian_transform_as_parent_frame: true

    # Frames
    base_link_frame: base_link
    gps_frame: gps_link
    odom_frame: odom
    world_frame: utm
