<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 
    Chassis Component
    
    This file defines the main structural elements of the mower:
    - base_link: Main chassis body (following reference structure)
    - counterweight: Rear counterweight for balance
    
    All dimensions and masses use properties from properties.xacro.
  -->

  <!-- Root Link (dummy link without inertia for KDL compatibility) -->
  <link name="base_footprint">
    <!-- No inertia on root link - KDL requirement -->
  </link>

  <!-- Fixed joint connecting root to actual chassis -->
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Base Link (main chassis) - now as child link with inertia -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <inertia ixx="${chassis_mass * (chassis_width*chassis_width + chassis_height*chassis_height) / 12}" 
               ixy="0.0" ixz="0.0" 
               iyy="${chassis_mass * (chassis_length*chassis_length + chassis_height*chassis_height) / 12}" 
               iyz="0.0" 
               izz="${chassis_mass * (chassis_length*chassis_length + chassis_width*chassis_width) / 12}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Counterweight Link -->
  <link name="counterweight">
    <visual>
      <geometry>
        <box size="${counterweight_length} ${counterweight_width} ${counterweight_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <box size="${counterweight_length} ${counterweight_width} ${counterweight_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${counterweight_mass}"/>
      <inertia ixx="${counterweight_mass * (counterweight_width*counterweight_width + counterweight_height*counterweight_height) / 12}" 
               ixy="0.0" ixz="0.0" 
               iyy="${counterweight_mass * (counterweight_length*counterweight_length + counterweight_height*counterweight_height) / 12}" 
               iyz="0.0" 
               izz="${counterweight_mass * (counterweight_length*counterweight_length + counterweight_width*counterweight_width) / 12}"/>
    </inertial>
  </link>

  <!-- Counterweight Joint -->
  <joint name="chassis_to_counterweight" type="fixed">
    <parent link="base_link"/>
    <child link="counterweight"/>
    <origin xyz="-${(chassis_length + counterweight_length)/2} 0.0 -${(chassis_height - counterweight_height)/2}" rpy="0 0 0"/>
  </joint>

</robot>
