<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 
    Cutting System Component
    
    This file defines the cutting and support system following the reference style:
    - front_roller: Front support roller
    - reel: Main cutting reel assembly  
    - reel_motor: Motor that drives the cutting reel
    
    All dimensions and masses use properties from properties.xacro.
  -->

  <!-- Front Roller Link -->
  <link name="front_roller">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${front_roller_radius}" length="${front_roller_width}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${front_roller_radius}" length="${front_roller_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${front_roller_mass}"/>
      <inertia ixx="${front_roller_mass * (3*front_roller_radius*front_roller_radius + front_roller_width*front_roller_width) / 12}" 
               ixy="0.0" ixz="0.0" 
               iyy="${front_roller_mass * front_roller_radius*front_roller_radius / 2}" 
               iyz="0.0" 
               izz="${front_roller_mass * (3*front_roller_radius*front_roller_radius + front_roller_width*front_roller_width) / 12}"/>
    </inertial>
  </link>

  <!-- Front Roller Joint -->
  <joint name="front_roller_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_roller"/>
    <origin xyz="0.48 0.0 -${chassis_height/2 + front_roller_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.5" friction="0.8"/>
  </joint>

  <!-- Reel Link -->
  <link name="reel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${reel_radius}" length="${reel_width}"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${reel_radius}" length="${reel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${reel_mass}"/>
      <inertia ixx="${reel_mass * (3*reel_radius*reel_radius + reel_width*reel_width) / 12}" 
               ixy="0.0" ixz="0.0" 
               iyy="${reel_mass * reel_radius*reel_radius / 2}" 
               iyz="0.0" 
               izz="${reel_mass * (3*reel_radius*reel_radius + reel_width*reel_width) / 12}"/>
    </inertial>
  </link>

  <!-- Reel Joint -->
  <joint name="reel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="reel"/>
    <origin xyz="0.30 0.0 -${chassis_height/2 - 0.02}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.8" friction="1.2"/>
  </joint>

  <!-- Reel Motor Link -->
  <link name="reel_motor">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${reel_motor_mass}"/>
      <inertia ixx="${reel_motor_mass * (0.05*0.05 + 0.05*0.05) / 12}" 
               ixy="0.0" ixz="0.0" 
               iyy="${reel_motor_mass * (0.05*0.05 + 0.05*0.05) / 12}" 
               iyz="0.0" 
               izz="${reel_motor_mass * (0.05*0.05 + 0.05*0.05) / 12}"/>
    </inertial>
  </link>

  <!-- Reel Motor Joint -->
  <joint name="chassis_to_reel_motor" type="fixed">
    <parent link="base_link"/>
    <child link="reel_motor"/>
    <origin xyz="0.125 0.11 0.04" rpy="0 0 0"/>
  </joint>

</robot>
