<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 
    Sensors Component
    
    This file defines the sensor systems for the mower:
    - IMU sensor: Inertial Measurement Unit for orientation and motion
    - GPS sensor: Global Positioning System for location tracking
    
    All positions use properties from properties.xacro.
  -->

  <!-- IMU Sensor Link -->
  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
      <material name="purple"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.000001" ixy="0.0" ixz="0.0" iyy="0.000001" iyz="0.0" izz="0.000001"/>
    </inertial>
  </link>

  <!-- IMU Sensor Joint -->
  <joint name="base_to_imu" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="${imu_x} ${imu_y} ${imu_z - wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- GPS Sensor Link -->
  <link name="gps_link">
    <visual>
      <geometry>
        <box size="0.03 0.03 0.04"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.03 0.03 0.04"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.000001" ixy="0.0" ixz="0.0" iyy="0.000001" iyz="0.0" izz="0.000001"/>
    </inertial>
  </link>

  <!-- GPS Sensor Joint -->
  <joint name="base_to_gps" type="fixed">
    <parent link="base_link"/>
    <child link="gps_link"/>
    <origin xyz="${gps_x} ${gps_y} ${gps_z - wheel_radius}" rpy="0 0 ${gps_yaw}"/>
  </joint>

  <!-- Gazebo IMU Sensor (native gz-sim format) -->
  <gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
      <always_on>1</always_on>
      <update_rate>70</update_rate>
      <visualize>true</visualize>
      <topic>imu</topic>
      <gz_frame_id>imu_link</gz_frame_id>
      <imu>
        <orientation_reference_frame>
          <localization>ENU</localization>
        </orientation_reference_frame>
        <enable_orientation>true</enable_orientation>
        <angular_velocity>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>0.0005</stddev>
              <bias_mean>0.0</bias_mean>
              <bias_stddev>0.0001</bias_stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>0.0005</stddev>
              <bias_mean>0.0</bias_mean>
              <bias_stddev>0.0001</bias_stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>0.0005</stddev>
              <bias_mean>0.0</bias_mean>
              <bias_stddev>0.0001</bias_stddev>
            </noise>
          </z>
        </angular_velocity>
        <linear_acceleration>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>0.005</stddev>
              <bias_mean>0.0</bias_mean>
              <bias_stddev>0.01</bias_stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>0.005</stddev>
              <bias_mean>0.0</bias_mean>
              <bias_stddev>0.01</bias_stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>0.005</stddev>
              <bias_mean>0.0</bias_mean>
              <bias_stddev>0.01</bias_stddev>
            </noise>
          </z>
        </linear_acceleration>
      </imu>
    </sensor>
  </gazebo>

  <!-- Gazebo GPS Sensor (native gz-sim format) -->
  <gazebo reference="gps_link">
    <sensor name="gps_sensor" type="navsat">
      <always_on>1</always_on>
      <update_rate>20</update_rate>
      <visualize>true</visualize>
      <topic>/gps/fix</topic>
      <gz_frame_id>gps_link</gz_frame_id>
      <navsat>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>
            <latitude>0.00000001</latitude>
            <longitude>0.00000001</longitude>
            <altitude>0.0000001</altitude>
          </stddev>
        </noise>
      </navsat>
    </sensor>
  </gazebo>

</robot>
